{
 "title": "cloudprobe",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "average-latency (20s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(latency[1m]) / rate(success[1m])",
     "legendFormat": "{{dst}},probe={{probe}}"
    }
   ]
  },
  {
   "title": "failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total-success", "legendFormat": "{{dst}},probe={{probe}}" }
   ]
  },
  {
   "title": "timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "timeouts", "legendFormat": "{{dst}},probe={{probe}}" }
   ]
  },
  {
   "title": "failure-ratio (20s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(total[1m]) - rate(success[1m])) / rate(total[1m])",
     "legendFormat": "{{dst}},probe={{probe}}"
    }
   ]
  },
  {
   "title": "timeouts rate (20s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(timeouts[1m])", "legendFormat": "{{dst}},probe={{probe}}" }
   ]
  },
  {
   "title": "sucess",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "success", "legendFormat": "{{dst}},probe={{probe}}" }
   ]
  }
 ]
}