apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-prober
  namespace: yunwei
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-prober
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "svc"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-prober
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-prober
  # name: admin
subjects:
  - kind: ServiceAccount
    name: service-prober
    namespace: yunwei
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-prober
  namespace: yunwei
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-prober
subjects:
  - kind: ServiceAccount
    name: service-prober
    namespace: yunwei
---
apiVersion: v1
kind: Service
metadata:
  name: service-prober
  namespace: yunwei
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9313"
spec:
  ports:
    - name: web
      port: 80
      targetPort: 9313
      protocol: TCP
  selector:
    app: service-prober

# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-prober
  namespace: yunwei
  annotations:
    # traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: prober.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: service-prober
              servicePort: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-prober
  namespace: yunwei
  labels:
    app: service-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-prober
  template:
    metadata:
      labels:
        app: service-prober
    spec:
      serviceAccountName: service-prober
      containers:
        - name: service-prober
          image: harbor.haodai.net/ops/service-prober:v1
          imagePullPolicy: Always
          # args:
          #   - -all
          #   - -server
          #   - 172.31.90.49:9314
          ports:
            - containerPort: 9314
          readinessProbe:
            tcpSocket:
              port: 9313
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9313
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: 0.5
              memory: 512M
            limits:
              cpu: 2
              memory: 4G

      nodeSelector:
        #kubernetes.io/hostname: 172.31.90.208
        func: monitor2
